### ISSUE TITLE
Wykrycie i obsługa rozłączenia gracza z GUI

### ISSUE THREAD

**Issue by rafixxx4k** [rafixxx4k/sieci_komputerowe_projekt#3]

**Comment by StaGlo** [comment]
The server is properly detecting that a player has disconnected and changes who to move if needed.
If cannot pass a move (no one to move), closes the room.

**Comment by StaGlo** [comment]
On the client side, the program is deleting (doesn't draw) disconnected players, however new players can spawn in strange positions (need to properly detect number of players to draw).

**Comment by StaGlo** [comment]
Improved disconnection handling on client side. Now there is an image sign instead of blank space.
